# Generated by Django 3.0.6 on 2020-05-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_a00_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_a00',
            name='contact_id',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
