# Generated by Django 3.0.6 on 2020-05-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200513_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_a00',
            name='contact_id',
            field=models.CharField(default='CON0000000001', max_length=50),
        ),
    ]
