# Generated by Django 3.0.6 on 2020-05-13 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200513_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_A01',
            fields=[
                ('contact_a01_rec', models.AutoField(primary_key=True, serialize=False)),
                ('contact_id', models.CharField(default='CON0000000001', max_length=50)),
                ('skill_id', models.IntegerField()),
                ('comments', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_A02',
            fields=[
                ('contact_a02_rec', models.AutoField(primary_key=True, serialize=False)),
                ('contact_id', models.CharField(default='CON0000000001', max_length=50)),
                ('endorsement_id', models.IntegerField()),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group_A00',
            fields=[
                ('Group_A00_Rec', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.CharField(default='GRP0000000001', max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=50)),
                ('barangay_district', models.CharField(max_length=50)),
                ('city_municipality', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('province', models.CharField(max_length=50)),
                ('phone_1', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^(09|\\+639)\\d{9}$')])),
                ('phone_2', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^(09|\\+639)\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group_A01',
            fields=[
                ('Group_A01_Rec', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.CharField(default='CON0000000001', max_length=50)),
                ('group_role', models.CharField(max_length=50)),
                ('comments', models.TextField()),
            ],
        ),
    ]
