# Generated by Django 3.0.6 on 2020-05-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contact_a01_contact_a02_group_a00_group_a01'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_a00',
            old_name='Group_A00_Rec',
            new_name='group_a00_rec',
        ),
        migrations.AddField(
            model_name='group_a01',
            name='contact_id',
            field=models.CharField(default='CON0000000001', max_length=50),
        ),
        migrations.AlterField(
            model_name='group_a01',
            name='group_id',
            field=models.CharField(default='GRP0000000001', max_length=50),
        ),
    ]
