# Generated by Django 3.0.6 on 2020-05-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20200513_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_a00',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact_a01',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact_a02',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group_a00',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group_a01',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
