# Generated by Django 3.0.6 on 2020-05-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20200513_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_a01',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
