# Generated by Django 3.0.6 on 2020-05-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_group_a01_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_a00',
            name='contact_id',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
