# Generated by Django 3.0.6 on 2020-05-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20200514_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_a01',
            old_name='Group_A01_Rec',
            new_name='group_a01_rec',
        ),
    ]
