# Generated by Django 2.2.10 on 2020-05-14 12:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_A01Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default='GRP0000000001', max_length=50)),
                ('contact_id', models.CharField(default='CON0000000001', max_length=50)),
                ('group_role', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('status', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('group_a01_rec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contact.Group_A01')),
            ],
        ),
        migrations.CreateModel(
            name='Group_A00Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default='GRP0000000001', max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=50)),
                ('barangay_district', models.CharField(max_length=50)),
                ('city_municipality', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('province', models.CharField(max_length=50)),
                ('phone_1', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^(09|\\+639)\\d{9}$')])),
                ('phone_2', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^(09|\\+639)\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('group_a00_rec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contact.Group_A00')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_A02Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(default='CON0000000001', max_length=50)),
                ('endorsement_id', models.IntegerField()),
                ('message', models.TextField()),
                ('status', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('contact_a02_rec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contact.Contact_A02')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_A01Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(default='CON0000000001', max_length=50)),
                ('skill_id', models.IntegerField()),
                ('comments', models.TextField()),
                ('status', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('contact_a01_rec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contact.Contact_A01')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_A00Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(default='CON0000000001', max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=50)),
                ('barangay_district', models.CharField(max_length=50)),
                ('city_municipality', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('province', models.CharField(max_length=50)),
                ('phone_1', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^(09|\\+639)\\d{9}$')])),
                ('phone_2', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^(09|\\+639)\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('contact_a00_rec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contact.Contact_A00')),
            ],
        ),
    ]
