# Generated by Django 3.0.6 on 2020-05-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_slave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_a00slave',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='contact_a01slave',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='contact_a02slave',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='group_a00slave',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='group_a01slave',
            name='status',
            field=models.BooleanField(),
        ),
    ]
